(function(){function f(){}function i(){this.pop=function(){throwError('env-pop "empty env"')};this.search=function(a){return new j(a)};this.peek=function(){throwError("env-peek")}}function h(){}function k(a,b,c){this.name=a;this.isBoxed=b;this.depth=c}function l(a,b,c){this.name=a;this.pos=c;this.depth=b}function j(a){this.name=a}function m(a,b){return-1<b.indexOf(a)?b.indexOf(a):!1}function o(){}function p(){}function d(a,b,c,g,q,r,s,t,e,f,h,i,j,k){this.env=a;this.modules=b;this.usedBindingsHash=
c;this.freeVariables=g;this.gensymCounter=q;this.providedNames=r;this.definedNames=s;this.sharedExpressions=t;this.withLocationEmits=e;this.allowRedefinition=f;this.moduleResolver=h;this.modulePathResolver=i;this.currentModulePath=j;this.declaredPermissions=k;this.isRedefinition=function(a){return this.env.lookup(a)};this.usedBindings=function(){return this.usedBindingsHash.values()};this.accumulateDeclaredPermission=function(a){return new d(this.env,this.modules,this.usedBindingsHash,this.freeVariables,
this.gensymCounter+1,this.providedNames,this.definedNames,this.sharedExpressions,this.withLocationEmits,this.allowRedefinition,this.moduleResolver,this.modulePathResolver,this.currentModulePath,[[a,m]].concat(this.declaredPermissions))};this.accumulateSharedExpression=function(a,b){var c=makeLabeledTranslation(this.gensymCounter,b);new d(this.env,this.modules,this.usedBindingsHash,this.freeVariables,this.gensymCounter+1,this.providedNames,this.definedNames,this.sharedExpressions.put(c,a),this.moduleResolver,
this.modulePathResolver,this.currentModulePath,this.declaredPermissions)};this.accumulateDefinedBinding=function(a,b){if(-1<u.indexOf(a.id))throwError(types.Message([new ColoredPart(a.id,b),": this is a reserved keyword and cannot be usedas a variable or function name"]));else if(!this.allowRedefinition&&isRedefinition(a.id)){var c=this.env.lookup(a.id);a.loc?throwError(types.Message([new ColoredPart(a.id,a.loc),": this name has a ",new ColoredPart("previous definition",c.loc)," and cannot be re-defined"])):
throwError(types.Message([new ColoredPart(a.id,a.loc),": this name has a ","previous definition"," and cannot be re-defined"]))}else return new d(envExtend(this.env,a),this.modules,this.usedBindingsHash,this.freeVariables,this.gensymCounter,this.providedNames,this.definedNames.put(a.id,a),this.sharedExpressions,this.withLocationEmits,this.allowRedefinition,this.moduleResolver,this.modulePathResolver,this.currentModulePath,this.declaredPermissions)};this.accumulateDefinedBindings=function(a,b){return a.reduce(function(a,
c){return this.accumulateDefinedBinding(c,b)},this)};this.accumulateModuleBindings=function(a){return a.reduce(function(a,b){return new a(envExtend(this.env,b),this.modules,this.usedBindingsHash,this.freeVariables,this.gensymCounter,this.providedNames,this.definedNames.put(b.id,b),this.sharedExpressions,this.withLocationEmits,this.allowRedefinition,this.moduleResolver,this.modulePathResolver,this.currentModulePath,this.declaredPermissions)},this)};this.accumulateModule=function(a){return new d(this.env,
[a].concat(this.modules),this.usedBindingsHash,this.freeVariables,this.gensymCounter,this.providedNames,this.definedNames,this.sharedExpressions,this.withLocationEmits,this.allowRedefinition,this.moduleResolver,this.modulePathResolver,this.declaredPermissions)};this.accumulateBindingUse=function(a){return new d(this.env,this.modules,this.usedBindingsHash.put(a.id,a),this.freeVariables,this.gensymCounter,this.providedNames,this.definedNames,this.sharedExpressions,this.withLocationEmits,this.allowRedefinition,
this.moduleResolver,this.modulePathResolver,this.currentModulePath,this.declaredPermissions)};this.accumulateFreeVariableUse=function(a){return new d(this.env,this.modules,this.usedBindingsHash,-1<this.freeVariables.indexOf(a)?this.freeVariables:[a].concat(this.freeVariables),this.gensymCounter,this.providedNames,this.definedNames,this.sharedExpressions,this.withLocationEmits,this.allowRedefinition,this.moduleResolver,this.modulePathResolver,this.currentModulePath,this.declaredPermissions)};this.gensym=
function(a){return[new d(this.env,this.modules,this.usedBindingsHash,this.freeVariables,this.gensymCounter+1,this.providedNames,this.definedNames,this.sharedExpressions,this.withLocationEmits,this.allowRedefinition,this.moduleResolver,this.modulePathResolver,this.currentModulePath,this.declaredPermissions),a+this.gensymCounter]};this.permissions=function(){function a(b){return 0===b.length?b:-1<b.slice(1).indexOf(b[0])?a.slice(1):[b[0]].concat(a.slice(1))}return a(this.usedBindings().reduce(function(a,
b){if(b.isFunction)return b.functionPermissions.concat(a);if(b.isConstant)return b.constantPermissions.concat(a)},[]))};this.getBasePinfo=function(a){var b=n();"moby"===Language?b.env=extendEnv_ModuleBinding(getTopLevelEnv(a),mobyModuleBinding):"base"===Language&&(b.env=getTopLevelEnv(a));return b}}function n(){return new d(new i,[],types.makeLowLevelEqHash(),[],0,types.makeLowLevelEqHash(),types.makeLowLevelEqHash(),types.makeLowLevelEqHash(),!0,!0,new o,new p,v,[])}function e(a,b){var c=[[],b||
n()];return a.reduce(function(a,b){var c=b.desugar(a[1]);a[0].push(c[0]);return[a[0],c[1]]},c)}var u="cond,else,let,case,let*,letrec,quote,quasiquote,unquote,unquote-splicing,local,begin,if,or,and,when,unless,lambda,\u03bb,define,define-struct,define-values".split(",");i.prototype=heir(f.prototype);(function(a,b,c){this.name=a;this.isBoxed=b;this.parentEnv=c;this.search=function(a,b){return a===this.name?function(b){return new l(a,dept,b)}:this.parentEnv.lookup(a,b+1)}}).prototype=heir(f.prototype);
(function(a,b){this.names=a;this.parentEnv=b;this.search=function(a,b){return m(a,this.names)?new k(a,this.isBoxed,this.depth):this.parentEnv.lookup(a,b)}}).prototype=heir(f.prototype);(function(a){this.parentEnv=a;this.search=function(a,c){return this.parentEnv.lookup(a,c-1)}}).prototype=heir(f.prototype);k.prototype=heir(h.prototype);l.prototype=heir(h.prototype);j.prototype=heir(h.prototype);var v="";Program.prototype.desugar=function(a){return[this,a]};defFunc.prototype.desugar=function(a){a=
this.body.desugar(a);return[new defFunc(this.name,this.args,a[0]),a[1]]};defVar.prototype.desugar=function(a){a=this.expr.desugar(a);return[new defVar(this.name,a[1]),a[1]]};defVars.prototype.desugar=function(){throw"desugaring defVars is not yet implemented";};defStruct.prototype.desugar=function(){throw"desugaring defStruct is not yet implemented";};beginExpr.prototype.desugar=function(a){a=e(this.exprs,a);return[new beginExpr(a[0]),a[1]]};lambdaExpr.prototype.desugar=function(a){a=this.body.desugar(a);
return[new lambdaExpr(this.args,a[0]),a[1]]};localExpr.prototype.desugar=function(a){e(this.defs,a);this.body.desugar(a);throw"desugaring defStruct is not yet implemented";};callExpr.prototype.desugar=function(a){a=e([this.func].concat(this.args),a);return[new callExpr(a[0][0],a[0].slice(1)),a[1]]};ifExpr.prototype.desugar=function(a){a=e([this.predicate,this.consequence,this.alternative],a);return[new ifExpr(a[0][0],a[0][1],a[0][2]),a[1]]};letrecExpr.prototype.desugar=function(a){return[new localExpr(this.bindings.map(function(a){return new defVar(a.first,
a.second.desugar())}),this.body.desugar()),a]};letExpr.prototype.desugar=function(a){var b=this.bindings.map(coupleFirst),c=this.bindings.map(coupleSecond);return(new callExpr(new lambdaExpr(b,this.body),c)).desugar(a)};letStarExpr.prototype.desugar=function(a){for(var b=this.body,c=0;c<this.bindings.length;c++)b=new letExpr([this.bindings[c]],b);return b.desugar(a)};condExpr.prototype.desugar=function(a){for(var b=this.clauses[this.clauses.length-1].second,c=this.clauses.length-2;-1<c;c--)b=new ifExpr(this.clauses[c].first,
this.clauses[c].second,b);return b.desugar(a)};andExpr.prototype.desugar=function(a){for(var b=this.exprs[exprs.length-1],c=this.exprs.length-2;-1<c;c--)b=new ifExpr(this.exprs[c],b,new booleanExpr(types.symbol("false")));return b.desugar(a)};orExpr.prototype.desugar=function(a){for(var b=exprs[exprs.length-1],c=this.exprs.length-2;-1<c;c--)b=new ifExpr(this.exprs[c],new booleanExpr(types.symbol("true")),b);return b.desugar(a)};Program.prototype.collectDefinitions=function(a){return a};defFunc.prototype.collectDefinitions=
function(){};defVar.prototype.collectDefinitions=function(){};defVars.prototype.collectDefinitions=function(){};defStruct.prototype.collectDefinitions=function(){};req.prototype.collectDefinitions=function(){};Program.prototype.collectProvides=function(a){return a};provideStatement.prototype.collectProvides=function(a){return a};Program.prototype.analyzeUses=function(a){return a};defFunc.prototype.analyzeUses=function(){};defVar.prototype.analyzeUses=function(){};defVars.prototype.analyzeUses=function(){};
defStruct.prototype.analyzeUses=function(){};beginExpr.prototype.analyzeUses=function(){};lambdaExpr.prototype.analyzeUses=function(){};localExpr.prototype.analyzeUses=function(){};callExpr.prototype.analyzeUses=function(){};ifExpr.prototype.analyzeUses=function(){};symbolExpr.prototype.analyzeUses=function(){};listExpr.prototype.analyzeUses=function(){};quasiquotedExpr.prototype.analyzeUses=function(){};qqList.prototype.analyzeUses=function(){};primop.prototype.analyzeUses=function(){};Program.prototype.compile=
function(a){return[this.val,a]};defFunc.prototype.compile=function(){throw"not implemented";};defVar.prototype.compile=function(){throw"not implemented";};defVars.prototype.compile=function(){throw"not implemented";};beginExpr.prototype.compile=function(){throw"not implemented";};lambdaExpr.prototype.compile=function(){throw"not implemented";};localExpr.prototype.compile=function(){throw"compiling locals is not implemented";};callExpr.prototype.compile=function(){throw"compiling calls is not implemented";
};ifExpr.prototype.compile=function(){throw"not implemented";};symbolExpr.prototype.compile=function(){throw"not implemented";};listExpr.prototype.compile=function(){};quotedExpr.prototype.compile=function(){};qqList.prototype.compile=function(){};primop.prototype.compile=function(){};quasiquotedExpr.prototype.compile=function(){};req.prototype.compile=function(){};provideStatement.prototype.compile=function(){};defStruct.prototype.compile=function(){throw"IMPOSSIBLE: define-struct should have been desugared";
};letStarExpr.prototype.compile=function(){throw"IMPOSSIBLE: letrec should have been desugared";};letExpr.prototype.compile=function(){throw"IMPOSSIBLE: let should have been desugared";};letStarExpr.prototype.compile=function(){throw"IMPOSSIBLE: let* should have been desugared";};letStarExpr.prototype.compile=function(){throw"IMPOSSIBLE: cond should have been desugared";};andExpr.prototype.compile=function(){throw"IMPOSSIBLE: and should have been desugared";};orExpr.prototype.compile=function(){throw"IMPOSSIBLE: or should have been desugared";
};window.analyze=function(a){programAnalyzeWithPinfo(a,getBasePinfo("base"))};window.compile=function(a,b){function c(a,b){var c=b.compile(a[1]),d=c[1];return[[c[0]].concat(a[0]),d]}var g=desugar(a,b),a=g[0],b=g[1],b=programAnalyzeWithPinfo(a,b);makeModulePrefixAndEnv(b);var d=a.filter(isDefinition),g=a.filter(function(a){return a instanceof req});a.filter(function(a){return a instanceof provideStatement});var e=a.filter(isExpression),b=g.reduce(c,[[],b])[1],f=d.reduce(c,[[],b]),d=f[0],b=f[1],e=e.reduce(c,
[[],b]),f=e[0],b=e[1],g=bcode-make-seq(compiled-g.concat(d,f));return[bcode-make-compilation-top(0,toplevel-prefix,g),b]};window.desugar=e})();
