(function(){function h(a){return a instanceof Constant&&types.isString(a.val)}function i(a){return a instanceof Constant&&types.isNumber(a.val)}function e(a){return a instanceof symbolExpr}function t(a){return a.map(function(a){if(j(a)||k(a)||l(a))a=q(a);else if(!j(a)&&!k(a)&&!l(a)&&!r(a)&&!s(a))a=b(a);else if(r(a)){var c=a[1],c=h(c)||e(c)?new req(c):isSymbolEqualTo(c[0],"lib")?new req(c):new req(cons("planet",cons(second(c),[rest(third(c))])));req.location=a.location;a=c}else s(a)?(c=new provideStatement(e(a[1])?
rest(a):"all-defined-out"),c.location=a.location,a=c):a=throwError(new types.Message(["Not a Definition, Expression, Library Require, or Provide"]),a.location);return a})}function j(a){return isCons(a)&&3===a.length&&e(a[0])&&isSymbolEqualTo("define-struct",a[0])}function k(a){return isCons(a)&&3===a.length&&e(a[0])&&isSymbolEqualTo("define",a[0])&&isCons(a[1])}function l(a){return isCons(a)&&3===a.length&&e(a[0])&&isSymbolEqualTo("define",a[0])&&!isCons(a[1])}function q(a){var e=j(a)?new defStruct(f(a[1]),
a[2].map(f)):k(a)?0<rest(a[1]).length?new defFunc(f(a[1][0]),rest(a[1]).map(f),b(a[2])):throwError(new types.Message(["expected at least one argument name after the function name, but found none."]),a.location):l(a)?new defVar(f(a[1]),b(a[2])):throwError(new types.Message(["Expected to find a definition, but found: "+a]),a.location);e.location=a.location;return e}function b(a){if(isCons(a))a=u(a);else{var b=h(a)?new stringExpr(a):i(a)?new numberExpr(a):isSymbolEqualTo("quote",a)?new quotedExpr(a):
m(a)?new charExpr(a.val):isSymbolEqualTo("true",a)||isSymbolEqualTo("false",a)?new booleanExpr(a):isSymbolEqualTo("empty",a)?new callExpr(new primop("list"),[]):e(a)?primitive.getPrimitive(a)?new primop(a):a:imageP(a)?new imageExpr(encodeImage(a),imageWidth(a),imageHeight(a),pinholeX(a),pinholeY(a)):throwError(new types.Message([a+"expected a function, but nothing's there"]),a.location);b.location=a.location;a=b}return a}function u(a){function p(a){return isCons(a)?new callExpr(b(a[0]),rest(a).map(b)):
throwError(new types.Message(["function call sexp"]),a.location)}function c(a){return new quotedExpr(isEmpty(a)?new callExpr(new primop("list"),[]):isCons(a)?new callExpr(new primop("list"),a.map(c)):i(a)?new numberExpr(a):h(a)?new stringExpr(a):m(a)?new charExpr(a.val):e(a)?new symbolExpr(a):throwError(new types.Message(["quoted sexp"]),a.location))}return function(){var d=a[0],d=!e(d)?p(a):isSymbolEqualTo("lambda",d)?g(a,"lambda",3)?-1<a[1].length?new lambdaExpr(a[1].map(f),b(a[2])):throwError(new types.Message(["expected at least one argument name in the sequence after `lambda', but found none"]),
a.location):throwError(new types.Message(["lambda function sexp"]),a.location):isSymbolEqualTo("local",d)?g(a,"local",3)?new localExpr(a[1].map(q),b(a[2])):throwError(new types.Message(["local expression sexp"]),a.location):isSymbolEqualTo("letrec",d)?g(a,"letrec",3)?new letrecExpr(a[1].map(n),b(a[2])):throwError(new types.Message(["letrec expression sexp"]),a.location):isSymbolEqualTo("let",d)?g(a,"let",3)?new letExpr(a[1].map(n),b(a[2])):throwError(new types.Message(["let expression sexp"]),a.location):
isSymbolEqualTo("let*",d)?g(a,"let*",3)?new letStarExpr(a[1].map(n),b(a[2])):throwError(new types.Message(["let* expression sexp"]),a.location):isSymbolEqualTo("cond",d)?v(a):isSymbolEqualTo("if",d)?g(a,"if",4)?new ifExpr(b(a[1]),b(a[2]),b(a[3])):throwError(new types.Message(["if expression sexp"]),a.location):isSymbolEqualTo("begin",d)?isCons(a)&&e(a[0])&&isSymbolEqualTo(a[0],"begin")?new beginExpr(rest(a).map(b)):throwError(new types.Message(["begin expression sexp"]),a.location):isSymbolEqualTo("and",
d)?isCons(a)&&e(a[0])&&isSymbolEqualTo(a[0],"and")?new andExpr(rest(a).map(b)):throwError(new types.Message(["and expression sexp"]),a.location):isSymbolEqualTo("or",d)?isCons(a)&&e(a[0])&&isSymbolEqualTo(a[0],"or")?new orExpr(rest(a).map(b)):throwError(new types.Message(["or expression sexp"]),a.location):isSymbolEqualTo("time",d)?g(a,"time",2)?new timeExpr(b(a[1])):throwError(new types.Message(["time expression sexp"]),a.location):isSymbolEqualTo("quote",d)?c(a[1]):isSymbolEqualTo("quasiquote",
d)?o(a[1],!1):p(a);d.location=a.location;return d}()}function v(a){if(isCons(a)&&2<=a.length&&e(a[0])&&isSymbolEqualTo(a[0],"cond"))return new condExpr(rest(a).reduceRight(function(a,c){var d;if(e(c[0])&&isSymbolEqualTo(c[0],"else")&&!isEmpty(a))d=throwError(new types.Message(["found an `else' clause that isn't the last clause in its `cond' expression"]),c.location);else{d=cons;var f;isCons(c)&&2===c.length?(f=new couple(b(c[0]),b(c[1])),f.location=c.location):f=throwError(new types.Message(["couple of expressions sexp"]),
c.location);d=d(f,a)}return d},[]));throwError(new types.Message(["cond expression sexp"]),a.location)}function n(a){return isCons(a)&&2===a.length?new couple(f(a[0]),b(a[1])):throwError(new types.Message(["couple of an id and an expression sexp"]),a.location)}function o(a,b){return isEmpty(a)?new qqList([]):isCons(a)?w(a,b):i(a)?new numberExpr(a):h(a)?new stringExpr(a):m(a)?new charExpr(a.val):e(a)?new symbolExpr(a):throwError(new types.Message(["quoted sexp"]),a.location)}function w(a,f){return e(a[0])?
isSymbolEqualTo(a[0],"unquote")?b(a[1]):isSymbolEqualTo(a[0],"unquote-splicing")?f?new qqSplice(b(a[1])):throwError(new types.Message(["misuse of ,@ or `unquote-splicing' within a quasiquoting backquote"]),a.location):new qqList(a.map(function(a){return o(a,!0)})):new qqList(a.map(function(a){return o(a,!0)}))}function f(a){return e(a)?a:throwError(new types.Message(["ID"]),a.location)}function g(a,b,c){return isCons(a)&&a.length===c&&e(a[0])&&isSymbolEqualTo(a[0],b)}function r(a){return isCons(a)&&
e(a[0])&&isSymbolEqualTo(a[0],"require")}function s(a){return isCons(a)&&e(a[0])&&isSymbolEqualTo(a[0],"provide")}var m=types.isChar;window.parse=function(a){return isEmpty(a)?[]:!isCons(a)?throwError(new types.Message(["The sexp is not a list of definitions or expressions: "+a]),a.location):t(a)}})();
