(function(){function h(a){return a instanceof Constant&&types.isString(a.val)}function i(a){return a instanceof Constant&&types.isNumber(a.val)}function e(a){return a instanceof symbolExpr}function u(a){return a.map(function(a){if(j(a)||k(a)||l(a))a=r(a);else if(!j(a)&&!k(a)&&!l(a)&&!s(a)&&!t(a))a=c(a);else if(s(a)){var d=a[1],d=h(d)||e(d)?new req(d):isSymbolEqualTo(d[0],types.symbol("lib"))?new req(d):new req(cons(types.symbol("planet"),cons(second(d),[rest(third(d))])));req.location=a.location;
a=d}else t(a)?(d=new provideStatement(e(a[1])?rest(a):types.symbol("all-defined-out")),d.location=a.location,a=d):a=throwError(new types.Message(["Not a Definition, Expression, Library Require, or Provide"]),a.location);return a})}function j(a){return isCons(a)&&3===a.length&&e(a[0])&&isSymbolEqualTo(types.symbol("define-struct"),a[0])}function k(a){return isCons(a)&&3===a.length&&e(a[0])&&isSymbolEqualTo(types.symbol("define"),a[0])&&isCons(a[1])}function l(a){return isCons(a)&&3===a.length&&e(a[0])&&
isSymbolEqualTo(types.symbol("define"),a[0])&&!isCons(a[1])}function r(a){var e=j(a)?new defStruct(f(a[1]),a[2].map(f)):k(a)?0<rest(a[1]).length?new defFunc(f(a[1][0]),rest(a[1]).map(f),c(a[2])):throwError(new types.Message(["expected at least one argument name after the function name, but found none."]),a.location):l(a)?new defVar(f(a[1]),c(a[2])):throwError(new types.Message(["Expected to find a definition, but found: "+a]),a.location);e.location=a.location;return e}function c(a){if(isCons(a))a=
v(a);else{var c=h(a)?new stringExpr(a):i(a)?new numberExpr(a):isSymbolEqualTo(types.symbol("quote"),a)?new quotedExpr(a):m(a)?new charExpr(a.val):isSymbolEqualTo(types.symbol("true"),a)||isSymbolEqualTo(types.symbol("false"),a)?new booleanExpr(a):isSymbolEqualTo(types.symbol("empty"),a)?new callExpr(new primop(types.symbol("list")),[]):e(a)?primitive.getPrimitive(a)?new primop(a):a:imageP(a)?new imageExpr(encodeImage(a),imageWidth(a),imageHeight(a),pinholeX(a),pinholeY(a)):throwError(new types.Message([a+
"expected a function, but nothing's there"]),a.location);c.location=a.location;a=c}return a}function v(a){function q(a){return isCons(a)?new callExpr(c(a[0]),rest(a).map(c)):throwError(new types.Message(["function call sexp"]),a.location)}function d(a){return new quotedExpr(isEmpty(a)?new callExpr(new primop(types.symbol("list")),[]):isCons(a)?new callExpr(new primop(types.symbol("list")),a.map(d)):i(a)?new numberExpr(a):h(a)?new stringExpr(a):m(a)?new charExpr(a.val):e(a)?new symbolExpr(a):throwError(new types.Message(["quoted sexp"]),
a.location))}return function(){var b=a[0];e(b)?isSymbolEqualTo(types.symbol("lambda"),b)?b=g(a,types.symbol("lambda"))?-1<a[1].length?new lambdaExpr(a[1].map(f),c(a[2])):throwError(new types.Message(["expected at least one argument name in the sequence after `lambda', but found none"]),a.location):throwError(new types.Message(["lambda function sexp"]),a.location):isSymbolEqualTo(types.symbol("local"),b)?b=g(a,types.symbol("local"))?new localExpr(a[1].map(r),c(a[2])):throwError(new types.Message(["local expression sexp"]),
a.location):isSymbolEqualTo(types.symbol("letrec"),b)?b=g(a,types.symbol("letrec"))?new letrecExpr(a[1].map(n),c(a[2])):throwError(new types.Message(["letrec expression sexp"]),a.location):isSymbolEqualTo(types.symbol("let"),b)?b=g(a,types.symbol("let"))?new letExpr(a[1].map(n),c(a[2])):throwError(new types.Message(["let expression sexp"]),a.location):isSymbolEqualTo(types.symbol("let*"),b)?b=g(a,types.symbol("let*"))?new letStarExpr(a[1].map(n),c(a[2])):throwError(new types.Message(["let* expression sexp"]),
a.location):isSymbolEqualTo(types.symbol("cond"),b)?b=w(a):isSymbolEqualTo(types.symbol("if"),b)?(b=types.symbol("if"),b=o(a,b,4)?new ifExpr(c(a[1]),c(a[2]),c(a[3])):throwError(new types.Message(["if expression sexp"]),a.location)):b=isSymbolEqualTo(types.symbol("begin"),b)?isCons(a)&&e(a[0])&&isSymbolEqualTo(a[0],types.symbol("begin"))?new beginExpr(rest(a).map(c)):throwError(new types.Message(["begin expression sexp"]),a.location):isSymbolEqualTo(types.symbol("and"),b)?isCons(a)&&e(a[0])&&isSymbolEqualTo(a[0],
types.symbol("and"))?new andExpr(rest(a).map(c)):throwError(new types.Message(["and expression sexp"]),a.location):isSymbolEqualTo(types.symbol("or"),b)?isCons(a)&&e(a[0])&&isSymbolEqualTo(a[0],types.symbol("or"))?new orExpr(rest(a).map(c)):throwError(new types.Message(["or expression sexp"]),a.location):isSymbolEqualTo(types.symbol("time"),b)?o(a,types.symbol("time"),2)?new timeExpr(c(a[1])):throwError(new types.Message(["time expression sexp"]),a.location):isSymbolEqualTo(types.symbol("quote"),
b)?d(a[1]):isSymbolEqualTo(types.symbol("quasiquote"),b)?p(a[1],!1):q(a):b=q(a);b.location=a.location;return b}()}function w(a){if(isCons(a)&&2<=a.length&&e(a[0])&&isSymbolEqualTo(a[0],types.symbol("cond")))return new condExpr(rest(a).reduceRight(function(a,d){var b;if(e(d[0])&&isSymbolEqualTo(d[0],types.symbol("else"))&&!isEmpty(a))b=throwError(new types.Message(["found an `else' clause that isn't the last clause in its `cond' expression"]),d.location);else{b=cons;var f;isCons(d)&&2===d.length?(f=
new couple(c(d[0]),c(d[1])),f.location=d.location):f=throwError(new types.Message(["couple of expressions sexp"]),d.location);b=b(f,a)}return b},[]));throwError(new types.Message(["cond expression sexp"]),a.location)}function n(a){return isCons(a)&&2===a.length?new couple(f(a[0]),c(a[1])):throwError(new types.Message(["couple of an id and an expression sexp"]),a.location)}function p(a,c){return isEmpty(a)?new qqList([]):isCons(a)?x(a,c):i(a)?new numberExpr(a):h(a)?new stringExpr(a):m(a)?new charExpr(a.val):
e(a)?new symbolExpr(a):throwError(new types.Message(["quoted sexp"]),a.location)}function x(a,f){return e(a[0])?isSymbolEqualTo(a[0],types.symbol("unquote"))?c(a[1]):isSymbolEqualTo(a[0],types.symbol("unquote-splicing"))?f?new qqSplice(c(a[1])):throwError(new types.Message(["misuse of ,@ or `unquote-splicing' within a quasiquoting backquote"]),a.location):new qqList(a.map(function(a){return p(a,!0)})):new qqList(a.map(function(a){return p(a,!0)}))}function f(a){return e(a)?a:throwError(new types.Message(["ID"]),
a.location)}function o(a,c,d){return isCons(a)&&a.length===d&&e(a[0])&&isSymbolEqualTo(a[0],c)}function g(a,c){return o(a,c,3)}function s(a){return isCons(a)&&e(a[0])&&isSymbolEqualTo(a[0],types.symbol("require"))}function t(a){return isCons(a)&&e(a[0])&&isSymbolEqualTo(a[0],types.symbol("provide"))}var m=types.isChar;window.parse=function(a){return isEmpty(a)?[]:!isCons(a)?throwError(new types.Message(["The sexp is not a list of definitions or expressions: "+a]),a.location):u(a)}})();
